---
- name: Close SNOW Call
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Update SNOW Incident/Change
    snow_record:
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: "{{ snow_state }}"
      number: "{{ incident_record_number }}"
      data:
        comments: "{{ snow_close_notes }}.  "
        state: 7
      table: "{{ snow_table }}"

