---
- hosts: localhost
  connection: local
  vars_files:
    - vars/telegram_vars.yml

  tasks:
    - name: Sending message to Telegram
      telegram: 
         token: "{{ tokenBot }}"
         chat_id: "{{ chatID }}"
         msg: "Ansible - interactive login for {{ host_or_group }} : {{ tty_on_off }}"

    - name: test gif 
      uri: 
        url: https://api.telegram.org/bot871909373:AAHYEA3ApjXXdvVm670GiYa7oEhdLm0WkNQ/sendVideo?chat_id=-1001160286622&video=https://media.giphy.com/media/dbtDDSvWErdf2/giphy.gif
        method: POST
